// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pyswvgtumkrmgfrazzdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5c3d2Z3R1bWtybWdmcmF6emRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTc4MDYsImV4cCI6MjA2OTg3MzgwNn0.cYjq7-J0Vot-yyJ8ZKx_4WmOEA9oCryO_JjouFS2n9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);